### ISSUE TITLE
Dart files missing ?

### ISSUE THREAD

**Issue by nsreenath** [matthew-carroll/flutter_ui_challenge_egg_timer#1]
Only `main.dart` is present in `master` branch, and it is empty!

![image](https://user-images.githubusercontent.com/3154529/38051268-6c722594-32eb-11e8-95ca-03741aa8380e.png)

![image](https://user-images.githubusercontent.com/3154529/38051305-84e8f2ec-32eb-11e8-810b-7e753dbfc80d.png)

**Comment by robertonic** [comment]
You need to check out the 'prototype' branch.

**Comment by matthew-carroll** [comment]
Hi, the branch from the video is “recording” so that’s probably the one you want.
